version: '3.7'
services:
  database:
    build:
      dockerfile: dockerfile
    # Weitere Konfigurationen für die Datenbank, wie Volumes und Umgebungsvariablen, können hier hinzugefügt werden.
    ports:
      - 27017:27017
    mem_limit: 2g
    memswap_limit: 2g
  backend:
    build:
      context: .
      dockerfile: dockerfile-backend
    ports:
      - 3000:3000
    depends_on:
      - database
    # volumes:
    #   - ./Pokemon.json:/app/Pokemon.json
      # Weitere Konfigurationen für das Backend, wie Ports und Umgebungsvariablen, können hier hinzugefügt werden.
    mem_limit: 2g
    memswap_limit: 2g

  frontend:
    build:
      context: .
      dockerfile: dockerfile-frontend
    ports:
      - 8080:8080
    mem_limit: 2g
    memswap_limit: 2g

    depends_on:
      - backend
    # Weitere Konfigurationen für das Frontend, wie Umgebungsvariablen, können hier hinzugefügt werden.
